from building import *
Import('rtconfig')

cwd = GetCurrentDir()
src	= Glob('*.c')
path = [cwd]

group = DefineGroup('qmp6989', src, depend = ['PKG_USING_QMP6989_DEMO'], CPPPATH = path)

Return('group')